import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEModal } from './EModal/Provider'

const DefaultComponent = () => {
  return (
    <div style={{width:'400px', height: '300px'}}>
      This is a example component
    </div>
  )
}

const Home: NextPage = () => {
  const { EM } = useEModal();

  const handlerClick = () => {
    EM().Open({
      title: 'Example Modal',
      content:  <DefaultComponent/>,
      options: [
        {
          text: 'NotExit', 
          close: false,
          act: ()=>alert('I told you.'),
        },
        {
          text: 'Exit',
          close: true,
          act: ()=>{}
        }
      ]
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handlerClick} >Try click it.</button>
      </main>
    </div>
  )
}

export default Home
