import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEModal } from './EModal/Provider'

const DefaultComponent = () => {
  return (
    <div style={{width:'400px', height: '300px'}}>
      This is a example component
    </div>
  )
}

const Home: NextPage = () => {
  const { EM } = useEModal();

  const openSubModal = () => {
    EM().Open({
      title: 'Sub Modal',
      content: (
        <div>
          <h1>Neasted Modal</h1>
          <button onClick={()=>EM().Clear()}>Close all</button>
          <button onClick={()=>EM().Close()}>Close this</button>
        </div>
      )
    })
  }

  const handlerClick = () => {
    EM().Open({
      title: 'Example Modal',
      content: <DefaultComponent/>,
      options: [
        {
          text: 'Open Sub Modal', 
          close: false,
          act: openSubModal,
        },
        {
          text: 'Exit',
          close: true,
          act: ()=>{}
        }
      ],
      configs: {
        NoCloseButton: true
      }
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handlerClick} >Try click it.</button>
      </main>
    </div>
  )
}

export default Home
