import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEModal } from './EModal/Provider'


const Home: NextPage = () => {
  const { EM } = useEModal();
  
  const DefaultComponent = () => {
    function Alert() {
      EM().Open({
        title: "Exemple Alert",
        defaultButtons: {
          left: {
            text: 'Accept', 
            close: true,
            act: ()=>alert("Another alert?!"),
          },
          right: {
            text: 'Decline',
            close: true
          }
        },
        configs: {
          NoCloseButton: true
        }
      })
    }

    return (
      <div style={{width:'400px', height: '300px'}}>
        <h5>
          This is a example component
        </h5>
        <button onClick={Alert}>Open Alert</button>
      </div>
    )
  }

  const openSubModal = () => {
    EM().Open({
      title: 'Sub Modal',
      content: (
        <div>
          <h1>Neasted Modal</h1>
          <button onClick={()=>EM().Clear()}>Close all</button>
          <button onClick={()=>EM().Close()}>Close this</button>
        </div>
      )
    })
  }

  const handlerClick = () => {
    EM().Open({
      content: <DefaultComponent/>,
      defaultButtons: {
        right: {
          text: 'Open Sub Modal', 
          close: false,
          act: openSubModal,
        },
        left: {
          text: 'Exit',
          close: true
        }
      },
      configs: {
        NoCloseButton: true
      }
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handlerClick} >Try click it.</button>
      </main>
    </div>
  )
}

export default Home
